### PR TITLE
[WIP] chore(links): normalize styles for all links

### PR DESCRIPTION
**Pull request by vikaspotluri123**
Nothing's super set in stone; there are multiple styles applied to links, and this PR normalizes it to blue underlined (in that order)

### CODE REVIEW

**Comment by AileenCGN** [comment]
Hey @vikaspotluri123 

We found that this blue is hardly readable sometimes and therefore went for green as the desired link colour, hence why it's green in the newer files (still needs to be changed in many places (e. g. [here](https://github.com/TryGhost/Ghost-CLI/blob/master/lib/ui/index.js#L340)) Maybe it's just the setup in my shell, but it was barely readable for me.

I think in general, we should be more consistent for this, so this PR is definitely is the right approach already.

@kirrg001 @acburdine Can we do a general specification on how our logs should be rendered?

- Type of error -> red
- Error message: "Message:"/"Stack:" -> yellow, text -> white
- help -> green
- debug information -> yellow

Did I miss something? Any suggestions?

**Comment by vikaspotluri123** [comment]
Yeah, I wasn't super sure what color to use so I just used the one I remember being most prominent, but I was definitely expecting some changes to be required 😄 

The default shells I use also make blue quite illegible on black, so no complaints with changing it here!

We might change help to light blue or cyan since green implies success 🤔

**Comment by vikaspotluri123** [comment]
Maybe do `inverse` for code blocks 🤔

**Comment by AileenCGN** [comment]
> We might change help to light blue or cyan since green implies success

Yeah, agree. I will check how we're doing the colours within Ghost core. Makes probably sense to keep it the same.

**Comment by vikaspotluri123** [comment]
I'm guessing we should also get feedback from @peterzimon 😅

**Comment by AileenCGN** [comment]
> I'm guessing we should also get feedback from @peterzimon

Yes, that is definitely something we can tackle in of our clean up weeks.

**Comment by vikaspotluri123** [comment]
Sounds good - when we get to it should we add a wrapper util for the different types?

**Pull request closed without merging**
