### PR TITLE
fix(mysql): improve password compatibility mysql user

### PR DESCRIPTION
**Pull request by gompa**
improve password compatibility with mysql password requirements
by adding the generate-password node module

### CODE REVIEW

**Comment by acburdine** [comment]
hmm...now that I'm looking at this regex it might actually have issues 😕 I'll test it out though and see if it works/doesn't.

**Comment by vikaspotluri123** [comment]
@acburdine imho the regex can be simplified to something like `^SET PASSWORD FOR 'ghost-[0-9]{1,4}'@'localhost' = PASSWORD\('.{10,}'\);$` (or can be condensed even more) - the tests are verifying queries and retries rather than a strong password is generated.

**Comment by vikaspotluri123** [comment]
Also sidenote: I think this is similar to (if not the same idea as) #517

**Comment by acburdine** [comment]
yeah it's a similar idea - we had a convo on Slack about this approach as well.

However, I figured out that the underlying issue wasn't actually the password itself (although that is a factor). The first issue we have to solve is that the `CREATE USER 'ghost-xx'@'localhost' IDENTIFIED WITH mysql_native_password` _also_ throws an error, before we even get to the secure password part.

That mysql_native_password thing was added to fix #396 - we need to ensure that whatever solution doesn't make that issue happen again.

**Comment by acburdine** [comment]
@gompa thanks for the fix! I went ahead and cherry-picked this commit and applied it to #546 -> I had to make some other changes alongside this one.

**Pull request closed without merging**
