### PR TITLE
feat: add --auto flag to make setup quicker

### PR DESCRIPTION
**Pull request by acburdine**
refs #806 

todo:
- [x] test w/more things
- [x] fix unit tests

### CODE REVIEW

**Comment by vikaspotluri123** [comment]
Finally got a chance to test 😄 

I created a clean VM (which means I can't set up SSL, but everything else works) and ran `ghost install`. I was only prompted for my URL, mysql credentials and sudo password (to create the ghost user).

Running it normally prompted for URL, mysql host, user pass, and db name, to create a mysql ghost user, to set up nginx, to set up ssl, to set up systemd and if I want to start ghost.

All this makes perfect sense 👌 

Running `ghost config --auto` asks me for the URL, MySQL host, user pass, and db - based on the spec:

> In ghost config the --auto flag switches to only prompt if there isn't a non-default value already set. E.g. it should be possible to configure all the mysql details, and then call ghost config and only be prompted for a url.

this doesn't seem to be happening - is this planned for a separate PR?

same question applies to `ghost setup --auto`

**Comment by acburdine** [comment]
> same question applies to `ghost setup --auto`

`ghost setup` calls `ghost config` under the hood so really it's just a matter of improving/fixing the first thing. The reason `ghost config --auto` still prompts for mysql credentials is that there _aren't_ defaults for those values,  you have to provide those manually. I'm working on a solution that should improve this usage, though.

**Comment by ErisDS** [comment]
Just given this a quick test. The behaviour of `ghost config --auto` is as expected 🎉 

However, `ghost setup --auto` is still prompting me for each stage, rather than assuming the default like `--no-prompt` does.

**Comment by acburdine** [comment]
@ErisDS I ran:

- `ghost install --no-setup`
- `ghost setup --auto`

I was, as expected, prompted for the url & mysql credentials, but I wasn't prompted for the setup stages (nginx, ssl, etc.). What series of commands did you run to get the behavior you were seeing?

**Comment by ErisDS** [comment]
I'm testing the main use case, which is a pre-filled install command. E.g. `ghost install --auto --db=mysql --dbhost=localhost --dbname=ghost_2 --dbuser=ghost etc` 

All of the config for the DB is provided.

**Comment by acburdine** [comment]
@ErisDS I ran that exact command (minus the `etc` part), and was still not able to reproduce. I was only prompted for the blog url and the ssl generation 😞.

**Comment by ErisDS** [comment]
I'm running it on a DO droplet e.g. not a local install - in case that helps

**Comment by ErisDS** [comment]
Managed to figure out what was wrong - this is good to go now.

**Pull request merged**
