### PR TITLE
🐛 Ensure all files are removed during uninstall

### LINKED ISSUE #811: `ghost uninstall` sometimes can't delete all content in directory
### Summary

If you get an issue where something gets created in your ghost install directory as root (such as on SSL verification), and then you try to run `ghost uninstall`, you'll get an error stating that it can't delete the directory (because it's owned by root)

### Steps to Reproduce

1. `ghost install`
2. SSL setup fails
3. `ghost uninstall`
4. Error, can't delete `system/files/.well-known`

This is because we're doing a simple `fs.remove` on the ghost install folder. Might be worth doing a `rm -rf` instead.

### PR DESCRIPTION
**Pull request by acburdine**
closes #811
- adds another task to unistall that removes root-owned files in the install directory

### CODE REVIEW

**Comment by acburdine** [comment]
@ErisDS @kirrg001 could I get a quick review on this?

**Comment by ErisDS** [comment]
How come the .well-known file gets created as root? Can we fix that?

**Comment by kirrg001** [comment]
> How come the .well-known file gets created as root?

I wanted to ask that too.

Furthermore, how can i reproduce this without creating the .well-known file manually?

**Comment by acburdine** [comment]
The `.well-known` directory gets created as root because we run `letsencrypt` with sudo (which is required to get the certs installed in `/etc/letsencrypt`)

**Comment by acburdine** [comment]
@kirrg001 you can reproduce by chowning one of the files in `<ghost dir>/system` to root, then trying `ghost uninstall`.

**Pull request closed without merging**
