### PR TITLE
Avoid direct upgrade to v2

### PR DESCRIPTION
**Pull request by kirrg001**
refs #759

- extend version resolver
- detect major version jumps
- optimised code structure (use proper force option - this was hard to maintain/understand)

- [x] add unit tests
- [x] do manual test

### CODE REVIEW

**Comment by kirrg001** [comment]
@acburdine This PR requires the implementation of the `--v1` flag support.

**Comment by vikaspotluri123** [comment]
Would we want to cache the results of the `yarn info` call? It seems wasteful to get all the versions of Ghost 2x 😛

**Comment by kirrg001** [comment]
Waiting for a merge of #772. Then i'll finalise and optimise this PR.

**Comment by kirrg001** [comment]
> Would we want to cache the results of the yarn info call? It seems wasteful to get all the versions of Ghost 2x 😛

Not sure i understand 🤔

**Comment by kirrg001** [comment]
I see. Yeah we can do that 👍

**Comment by kirrg001** [comment]
> Basically since versionResolver gets called twice (2x) there's no point in making the yarn call twice

I have changed the code - it was ugly to call the resolver twice. Cache is not needed anymore :)

**Comment by kirrg001** [comment]
@vikaspotluri123 @acburdine This is ready for review. Would be cool if you could double check if i have missed a case.

**Comment by kirrg001** [comment]
Okay i just discovered one case:

- You are on v2.
- You run `ghost update --force --v1`
- We should throw an error.
- Will add

**Comment by kirrg001** [comment]
> Okay i just discovered one case:

Added

**Comment by kirrg001** [comment]
I'll merge this into the 1.9 branch now. I'll open a new PR tomorrow to see all the changes from 1.9 and i'll add a QA list. If you have time helping with testing, let me know!

**Pull request merged**
