### PR TITLE
Add support for Proxy

### PR DESCRIPTION
**Pull request by cheahkhing**
Hi,

As per mentioned in #211 , i've created the fix for it. Please review and let me know if this is ok.
I tested from my corporate proxy, it works now. :)

### CODE REVIEW

**Comment by acburdine** [comment]
Hey @cheahkhing, apologies for not reviewing this sooner.

A few initial comments looking at this:
- The different version resolution functions were consolidated into one `utils/version.js` file, would you be able to update your code to match?
- Can you write some tests for this/update the existing tests to work with the additional logic?
- Is there a reason for using the tunnel package over something like https://github.com/TooTallNate/node-https-proxy-agent? seems like the https-proxy-agent supports the same things the tunnel library does, and it looks at first glance to be better maintained

**Comment by cheahkhing** [comment]
@acburdine Hi, thanks for reviewing, i'll try to pull latest and fix all the issues and submit the PR again then.
regarding the https-proxy-agent, i didn't look at it before, maybe i can try it out and see how.

**Comment by cheahkhing** [comment]
Hi @acburdine, i merged with the latest changes and fix some of the tests, not sure this is good enough. I am not so familiar with the structure of the tests, so if you could help out that will be nice.

Thanks.

**Comment by acburdine** [comment]
@cheahkhing would you be able to rebase your branch against the latest ghost master instead of merging? right now, it's incredibly difficult to tell your changes apart from all of the other changes made to Ghost-CLI since this PR was first created

**Comment by cheahkhing** [comment]
Hi @acburdine , i use the latest master and transfer my changes there with a new pull request: #1042 , please kindly review. i'll close this one.

**Pull request closed without merging**
