### PR TITLE
Fixed name

### PR DESCRIPTION
**Pull request by therecluse26**
The name Ghost-CLI is a huge missed opportunity, so I decided to fix it!

### CODE REVIEW

**Comment by acburdine** [comment]
@therecluse26 thank you for the suggestion - we actually titled a release of Ghost-CLI similarly in the past :smile: (https://github.com/TryGhost/Ghost-CLI/releases/tag/1.0.0-alpha.8)

That said, we won't be changing the name of the project - it was chosen deliberately.

**Comment by brad-tilmor** [comment]
@acburdine I am both filled with the fury of 10,000 suns and totally understanding of your decision

**Comment by therecluse26** [comment]
@acburdine I am both filled with the fury of 10,000 suns and totally understanding of your decision

**Comment by ErisDS** [comment]
To be fair though, where it doesn't hamper "typability" or "readability" we do love a good easter egg. The port number was chosen with great care, and there's fun to be found in `ghost --help` among other places 😬

**Pull request closed without merging**
