### PR TITLE
feat(flag): add --v1 flag to install and update

### PR DESCRIPTION
**Pull request by acburdine**
refs #759
- adds --v1 flag to install and update commands
- add arg to resolveVersion util that limits versions to 1.x releases

TODO:
- [x] manual testing
- [x] fix unit tests

### CODE REVIEW

**Comment by kirrg001** [comment]
I have tested the PR locally. Works nice 👍 

I've tested and mocked the 2.0 release in the code base:

`ghost install local` -> will install 2.0 if it's out
`ghost install local --v1` -> will install latest v1
`ghost install 1.22.0 --local` -> will install target v1 version
`ghost update --v1` -> will update to latest v1 release
`ghost update` -> will update to 2.0

🤠

**Comment by kirrg001** [comment]
Feel free to self-merge if you have added more tests!

**Comment by kirrg001** [comment]
I'll take this PR over. I want to merge it today 😇

**Comment by acburdine** [comment]
@kirrg001 will merge once travis is green, looks like the 1.9 rebase broke a couple tests 😬

**Pull request merged**
