### PR TITLE
Someone call for a doctor?

### LINKED ISSUE #312: `ghost install` doesn't run system checks early enough / `ghost doctor` is incomplete
The move towards extensions has broken from the original intention of the cli single `ghost install` command & `ghost doctor` commands. In terms of doing full stack checks up front.

When I run `ghost doctor` I expect it to perform all system checks, and tell me whether it's safe to run `ghost install` & perhaps even early indicate I should use `ghost install local`. It currently only checks the node version and folder permissions.

If `ghost doctor` says everything is A-OK, that should be a sign that `ghost install` will complete using the standard recommended flow (e.g. including mysql, nginx, etc).

When I run `ghost install`, I expect `ghost doctor` to happen first, running all the checks and giving me the option to proceed if at all possible.

Here's what happens if you try to install Ghost on a mac:

Note: everything starts of green and shiny and then gets yellower and scarier and suddenly we're talking about nginx.

My expectation would be that this message:

```
System Stack checks failed with message: 'Platform is not Linux'.
Some features of Ghost-CLI may not work without additional configuration.\
? Continue anyways? Yes
```

Would appear before ghost-cli attempted to do a download and install, and then got stuck into trying to do stuff with MySQL.

The reason is, people don't know how to use ghost-cli yet. It's a brand new tool, I anticipate many people installing it on their mac or windows box to try it out and getting started with `ghost install`, not realising that `ghost install local` is for them.

The ideal situation would be that this message would appear before the download, install and prompts, with an additional indicator to use `ghost install local`:

```
System Stack checks failed with message: 'Platform is not Linux'.
Some features of Ghost-CLI may not work without additional configuration.
For local installs we recommend using `ghost install local` instead.
? Continue anyways? Yes
```

I realise this will take a bit of a rejig, and prob needs to happen post 1.0 now, however I do believe we need to work toward this.

### PR DESCRIPTION
**Pull request by acburdine**
feat(doctor): ghost install/setup doctor check improvements
closes #312, #314
- move setup checks into install checks
- add checks for mysql
- improve doctor messaging

### CODE REVIEW

**Comment by ErisDS** [comment]
👍  this is looking great

image

**Comment by mathiasjakobsen** [comment]
@ErisDS, there seems to be a problem if one is installing Ghost headless. When passing `--no-prompt' as well as all database related flags, this is the output:

```log
[2017-07-31T12:33:25.906566Z]    
 Node.js version [started]
[2017-07-31T12:33:25.922775Z]    [12:33:25] Checking system Node.js version [completed]
[2017-07-31T12:33:25.926414Z]    [12:33:25] Checking current folder permissions [started]
[2017-07-31T12:33:25.928326Z]    [12:33:25] Checking current folder permissions [completed]
[2017-07-31T12:33:25.929416Z]    [12:33:25] Checking operating system [started]
[2017-07-31T12:33:25.929946Z]    [12:33:25] Checking operating system [skipped]
[2017-07-31T12:33:25.930409Z]    [12:33:25] Checking MySQL is installed [started]
[2017-07-31T12:33:26.295423Z]    Local MySQL install not found. You can ignore this if you are using a remote MySQL host.
[2017-07-31T12:33:26.295501Z]    Alternatively you could:
[2017-07-31T12:33:26.295642Z]    a) install MySQL locally
[2017-07-31T12:33:26.295656Z]    b) run `ghost install --db=sqlite3` to use sqlite 
[2017-07-31T12:33:26.295696Z]    c) run `ghost install local` to get a development install using sqlite3.
[2017-07-31T12:33:26.29766Z]     [12:33:26] Checking MySQL is installed [failed]
[2017-07-31T12:33:26.298298Z]    [12:33:26] → Prompts have been disabled, please provide options via command line flags
[2017-07-31T12:33:26.300151Z]    
Error occurred.
[2017-07-31T12:33:26.301327Z]    Message: Prompts have been disabled, please provide options via command line flags
[2017-07-31T12:33:26.301817Z]    Debug Information:
[2017-07-31T12:33:26.301844Z]        Node Version: v6.11.1
[2017-07-31T12:33:26.301928Z]        Ghost-CLI Version: 1.0.1
[2017-07-31T12:33:26.301942Z]        Environment: production
[2017-07-31T12:33:26.302001Z]        Command: 'ghost install --url --port 8080 --db mysql --dbhost leader.mariadb.discoverd --dbuser 2fb671eb80bd1ecd5208fc5bba610c9d --dbpass 2510285cbe65c8de7a5293552b70bf4b --dbname 379a9fdd190b027b381c313aa0f2b8f3 --start --no-prompt --no-stack'
[2017-07-31T12:33:26.30243Z]     Please refer to https://docs.ghost.org/docs/installing-ghost-via-the-cli#troubleshooting for troubleshooting.
[2017-07-31T12:33:26.310591Z] 
```

**Comment by acburdine** [comment]
@mathiasjakobsen yup - I noticed that before and forgot to open an issue for it, will fix.

**Comment by mathiasjakobsen** [comment]
@acburdine, awesome! Anyway of getting around it, until fixed?

**Comment by ErisDS** [comment]
Fix will likely be released faster than anyone could come up with a workaround. Hang tight ;)

**Pull request merged**
