### PR TITLE
More text-based tweaks 😁

### PR DESCRIPTION
**Pull request by ErisDS**
Raising this just to flag up that I have a handful of very minor text-based tweaks I'd like to make.
These are mostly dependent on docs urls, so need to finish updating docs a bit first.

In this PR so far I have swapped around the checks for pre 1.0.0 and dev installs - I haven't tested this, but short term it seems like pre 1.0.0 is more likely, and so should be the first message.

I'm also adding a link to the migration guide

### CODE REVIEW

**Comment by acburdine** [comment]
👍  Looks good so far

**Comment by ErisDS** [comment]
Think this one is done

**Comment by ErisDS** [comment]
NVM failed tests... looking

**Comment by acburdine** [comment]
Tests are failing because `yargs.epilogue` needs to be stubbed in the unit tests for the command class

**Comment by ErisDS** [comment]
Yar fixed 😁

**Comment by acburdine** [comment]
*yargs fixed :trollface:

**Pull request merged**
